name: Deploy on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH so that the runner can connect to your VPS
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Connect to your VPS and perform the deployment
      - name: Deploy on VPS using Docker
        run: |
          ssh -o StrictHostKeyChecking=no root@147.182.185.158 << 'EOF'
            set -e  # Exit immediately if any command fails

            # Navigate to your project directory on the VPS
            cd /path/to/your/project

            # Update the code to the latest master branch version
            git pull origin master

            # --- Build and Deploy Backend ---
            cd backend
            echo "Building backend Docker image..."
            docker build -t my-backend:latest .
            echo "Stopping and removing any running backend container..."
            docker rm -f my-backend || true
            echo "Running backend container..."
            docker run -d --name my-backend -p 4000:4000 my-backend:latest

            # --- Build and Deploy Frontend ---
            cd ../frontend
            echo "Building frontend Docker image..."
            docker build -t my-frontend:latest .
            echo "Stopping and removing any running frontend container..."
            docker rm -f my-frontend || true
            echo "Running frontend container..."
            docker run -d --name my-frontend -p 3000:3000 my-frontend:latest

            # --- Build and Deploy Model Service ---
            cd ../model
            echo "Building model Docker image..."
            docker build -t my-model:latest .
            echo "Stopping and removing any running model container..."
            docker rm -f my-model || true
            echo "Running model container..."
            docker run -d --name my-model -p 5000:5000 my-model:latest

          EOF
